build: Deploy via http

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -26,6 +26,7 @@ jobs:
 
     runs-on: ubuntu-latest
 
+    if: github.ref_name != 'main'
     steps:
     - uses: actions/checkout@v4
     - name: Set up JDK 17
@@ -40,7 +41,6 @@ jobs:
   deploy:
 
     runs-on: ubuntu-latest
-    needs: build
 
     if: github.ref_name == 'main'
     steps:
@@ -55,6 +55,23 @@ jobs:
       run: mvn -B clean install
     - name: Bundle
       run: mvn -B -f imagey-server/pom.xml meecrowave:bundle
+    - name: Upload bundle
+      run: |
+        echo "=== GitHub Runner File Check ==="
+        ls -lh imagey-server/target/ || echo "Target folder does not exist!"
+        
+        ZIP_FILE="imagey-server/target/imagey-server-meecrowave-distribution.zip"
+        if [ ! -f $ZIP_FILE ]; then
+          echo "ERROR: File does not exist!"
+          exit 1
+        fi
+        
+        DEPLOYMENT_SECRET="${{ secrets.DEPLOYMENT_SECRET }}"
+
+        curl --fail -X PUT \
+          -H "X-Deployment-Secret: $DEPLOYMENT_SECRET" \
+          -T "$ZIP_FILE" \
+          https://secure-doc.store/deployments
     - name: Copy bundle
       uses: appleboy/scp-action@v0.1.7
       with:
